In [274]:
import numpy as np

### Load dataset

In [293]:
from sklearn.datasets import load_iris
data = load_iris()
X, Y = data.data, data.target

In [294]:
# only classify class 1 vs class 2
idx = (Y > 0)
X = X[idx, :]
Y = Y[idx]
X,Y

(array([[7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6

### Data normalization
Remember: normalization is done per feature, not all at once. Also, remember that Y is [1, 2] instead of [0, 1].

In [295]:
# Write your code here. Don't forget the bias!
for i in range (0,4):
    X[:, i] = (X[:,i] - np.mean(X[:,i].T)) / np.std(X[:, i].T)
X = np.concatenate((np.ones((X.shape[0], 1)), X), axis = 1)
Y = Y - 1  # class 1,2

In [296]:
X, weight

(array([[ 1.        ,  1.11900931,  0.99068792, -0.25077906, -0.65303909],
        [ 1.        ,  0.20924564,  0.99068792, -0.49425387, -0.41643072],
        [ 1.        ,  0.96738203,  0.68864892, -0.00730424, -0.41643072],
        [ 1.        , -1.15539985, -1.72766308, -1.10294091, -0.88964745],
        [ 1.        ,  0.36087292, -0.21746808, -0.37251647, -0.41643072],
        [ 1.        , -0.8521453 , -0.21746808, -0.49425387, -0.88964745],
        [ 1.        ,  0.05761837,  1.29272692, -0.25077906, -0.17982236],
        [ 1.        , -2.06516352, -1.42562408, -1.95510276, -1.59947255],
        [ 1.        ,  0.5125002 ,  0.08457092, -0.37251647, -0.88964745],
        [ 1.        , -1.61028169, -0.51950708, -1.22467832, -0.65303909],
        [ 1.        , -1.91353624, -2.63378009, -1.71162795, -1.59947255],
        [ 1.        , -0.54889074,  0.38660992, -0.8594661 , -0.41643072],
        [ 1.        , -0.39726347, -2.02970209, -1.10294091, -1.59947255],
        [ 1.        , -0.

### Define classification model
Create parameters here. Initialize with zeros. In case you forgot: $Y = \sigma(X\Theta)$.

In [297]:
weight = np.zeros(X.shape[1])
weight

array([0., 0., 0., 0., 0.])

In [298]:
# learning rate
alpha = 1e-2
# epochs
epoch = 10000

In [299]:
def sigmoid(s):
    return 1/(1 + np.exp(-s))

In [300]:
def loss_function(X, Y, weight):
    z = sigmoid(X @ weight)
    return -np.sum(Y * np.log(z) + (1 - Y) *  np.log(1 - z)) / (Y.size)

In [301]:
def sgd(X, Y, weight, alpha, epoch):
    for i in range(10000):
        gd = (X.T @ (sigmoid(X @ weight) - Y)) / (Y.size)
        weight -= alpha * gd
    return weight
weight = sgd(X, Y, weight, alpha, epoch)
weight

array([ 0.12047504, -0.44156746, -0.89309501,  2.965364  ,  3.3427994 ])

### Define evaluation metrics

In [302]:
def accuracy(X, Y, weight):
    '''
    Evaluate the model, represented by `weight`, with data (X, Y).
    
    Input:
        X:      data features
        Y:      data labels
        weight: model weights
    Ouput:
        Model accuracy on input data.
    '''
    
    # implement your code here
    y_predict = []
    for i in sigmoid(X @ weight):
        if i > 0.5:
            y_predict.append(1)
        else: y_predict.append(0)
    return float(np.sum(Y == y_predict) / (Y.size)) 
y_predict = accuracy(X,Y,weight)
y_predict

0.96

### Hyperparameters

In [29]:
# learning rate
alpha = 1e-2
# epochs
epoch = 10000

### Train the model.

In [304]:
# just to double check
assert np.allclose(weight, np.array([0.12047504, -0.44156746, -0.89309501, 2.965364, 3.3427994]))

In [305]:
# model accuracy
accuracy(X, Y, weight)

0.96

### (Optional) How low can you go?
Do anything you want to get the best performance out of the training set. For once, let's overfit to your heart's content.

In [306]:
print('Weights:', weight)
y = 1 / (1 + np.exp(-X @ weight))
loss = -np.sum(Y * np.log(y) + (1 - Y) * np.log(1 - y))
print('Loss:', loss)
print('Accuracy:', accuracy(X, Y, weight))

Weights: [ 0.12047504 -0.44156746 -0.89309501  2.965364    3.3427994 ]
Loss: 8.662719407135402
Accuracy: 0.96
